import { Router, Response, Request } from "express";
import multer from "multer";
import { generateEditToken, generateEventID } from "../util/generator.js";
import { validateGroupData } from "../util/validation.js";
import Jimp from "jimp";
import { addToLog } from "../helpers.js";
import EventGroup from "../models/EventGroup.js";
import { marked } from "marked";
import { renderPlain } from "../util/markdown.js";
import { checkAuth, getConfigMiddleware } from "../lib/middleware.js";
import {
  clearFutureAutoGeneratedInstances,
  generateRecurringEvents,
} from "../lib/recurrence.js";

const storage = multer.memoryStorage();
// Accept only JPEG, GIF or PNG images, up to 10MB
const upload = multer({
  storage: storage,
  limits: { fileSize: 10 * 1024 * 1024 },
  fileFilter: function (_, file, cb) {
    const filetypes = /jpeg|jpg|png|gif/;
    const mimetype = filetypes.test(file.mimetype);
    if (!mimetype) {
      return cb(new Error("Only JPEG, PNG and GIF images are allowed."));
    }
    cb(null, true);
  },
});

const router = Router();

router.use(getConfigMiddleware);

router.post(
  "/group",
  upload.single("imageUpload"),
  checkAuth,
  async (req: Request, res: Response) => {
    const { data: groupData, errors } = validateGroupData(req.body);
    if (errors && errors.length > 0) {
      return res.status(400).json({ errors });
    }
    if (!groupData) {
      return res.status(400).json({
        errors: [
          {
            message: "No group data was provided.",
          },
        ],
      });
    }

    try {
      const groupID = generateEventID();
      const editToken = generateEditToken();
      let groupImageFilename;

      if (req.file?.buffer) {
        try {
          const img = await Jimp.read(req.file.buffer);
          img
            .resize(920, Jimp.AUTO) // resize
            .quality(80) // set JPEG quality
            .write("./public/events/" + groupID + ".jpg"); // save
          groupImageFilename = groupID + ".jpg";
        } catch (err) {
          addToLog(
            "Jimp",
            "error",
            "Attempt to edit image failed with error: " + err,
          );
        }
      }

      const isNthWeekday = groupData.recurrenceMonthlyType === "nth-weekday";
      const recurrence = groupData.recurrenceEnabled
        ? {
            enabled: true,
            frequency: groupData.recurrenceFrequency as
              | "weekly"
              | "biweekly"
              | "monthly",
            dayOfWeek: isNthWeekday
              ? groupData.recurrenceNthDayOfWeek !== undefined
                ? Number(groupData.recurrenceNthDayOfWeek)
                : undefined
              : groupData.recurrenceDayOfWeek !== undefined
                ? Number(groupData.recurrenceDayOfWeek)
                : undefined,
            monthlyType: (groupData.recurrenceMonthlyType || "day-of-month") as
              | "day-of-month"
              | "nth-weekday",
            dayOfMonth:
              groupData.recurrenceDayOfMonth !== undefined
                ? Number(groupData.recurrenceDayOfMonth)
                : undefined,
            nth:
              groupData.recurrenceNth !== undefined
                ? Number(groupData.recurrenceNth)
                : undefined,
            time: groupData.recurrenceTime!,
            timezone: groupData.recurrenceTimezone!,
            durationMinutes: Number(groupData.recurrenceDurationMinutes),
          }
        : undefined;

      const eventGroup = new EventGroup({
        id: groupID,
        name: groupData.eventGroupName,
        description: groupData.eventGroupDescription,
        image: groupImageFilename,
        creatorEmail: groupData.creatorEmail,
        url: groupData.eventGroupURL,
        hostName: groupData.hostName,
        editToken: editToken,
        firstLoad: true,
        showOnPublicList: groupData.publicBoolean,
        recurrence,
      });

      await eventGroup.save();

      if (recurrence?.enabled) {
        generateRecurringEvents().catch((err) =>
          console.error(
            "Recurrence generation failed after group create:",
            err,
          ),
        );
      }

      addToLog(
        "createEventGroup",
        "success",
        "Event group " + groupID + " created",
      );

      // Send email with edit link
      if (groupData.creatorEmail) {
        req.emailService.sendEmailFromTemplate({
          to: groupData.creatorEmail,
          subject: eventGroup.name,
          templateName: "createEventGroup",
          templateData: {
            eventGroupID: eventGroup.id,
            editToken: eventGroup.editToken,
          },
        });
      }

      res.status(200).json({
        id: groupID,
        editToken: editToken,
        url: `/group/${groupID}?e=${editToken}`,
      });
    } catch (err) {
      console.error(err);
      addToLog(
        "createEvent",
        "error",
        "Attempt to create event failed with error: " + err,
      );
      return res.status(500).json({
        errors: [
          {
            message: err,
          },
        ],
      });
    }
  },
);

router.put(
  "/group/:eventGroupID",
  upload.single("imageUpload"),
  async (req: Request, res: Response) => {
    const { data: groupData, errors } = validateGroupData(req.body);
    if (errors && errors.length > 0) {
      return res.status(400).json({ errors });
    }
    if (!groupData) {
      return res.status(400).json({
        errors: [
          {
            message: "No group data was provided.",
          },
        ],
      });
    }

    try {
      const submittedEditToken = req.body.editToken;
      const eventGroup = await EventGroup.findOne({
        id: req.params.eventGroupID,
      });
      if (!eventGroup) {
        return res.status(404).json({
          errors: [
            {
              message: "Event group not found.",
            },
          ],
        });
      }

      if (eventGroup.editToken !== submittedEditToken) {
        // Token doesn't match
        addToLog(
          "editEventGroup",
          "error",
          `Attempt to edit event group ${req.params.eventGroupID} failed with error: token does not match`,
        );
        return res.status(403).json({
          errors: [
            {
              message: "Edit token is invalid.",
            },
          ],
        });
      }
      // Token matches
      // If there is a new image, upload that first
      const eventGroupID = req.params.eventGroupID;
      let eventGroupImageFilename = eventGroup.image;
      if (req.file?.buffer) {
        try {
          const img = await Jimp.read(req.file.buffer);
          img
            .resize(920, Jimp.AUTO) // resize
            .quality(80) // set JPEG quality
            .write(`./public/events/${eventGroupID}.jpg`); // save
        } catch (err) {
          addToLog(
            "Jimp",
            "error",
            "Attempt to edit image failed with error: " + err,
          );
        }

        eventGroupImageFilename = eventGroupID + ".jpg";
      }

      const isNthWeekdayUpdate =
        groupData.recurrenceMonthlyType === "nth-weekday";
      const updatedRecurrence = groupData.recurrenceEnabled
        ? {
            enabled: true,
            frequency: groupData.recurrenceFrequency as
              | "weekly"
              | "biweekly"
              | "monthly",
            dayOfWeek: isNthWeekdayUpdate
              ? groupData.recurrenceNthDayOfWeek !== undefined
                ? Number(groupData.recurrenceNthDayOfWeek)
                : undefined
              : groupData.recurrenceDayOfWeek !== undefined
                ? Number(groupData.recurrenceDayOfWeek)
                : undefined,
            monthlyType: (groupData.recurrenceMonthlyType || "day-of-month") as
              | "day-of-month"
              | "nth-weekday",
            dayOfMonth:
              groupData.recurrenceDayOfMonth !== undefined
                ? Number(groupData.recurrenceDayOfMonth)
                : undefined,
            nth:
              groupData.recurrenceNth !== undefined
                ? Number(groupData.recurrenceNth)
                : undefined,
            time: groupData.recurrenceTime!,
            timezone: groupData.recurrenceTimezone!,
            durationMinutes: Number(groupData.recurrenceDurationMinutes),
          }
        : undefined;

      // If the rule's shape changed in a way that moves future occurrences
      // (frequency, weekday, time, timezone, monthly mode, etc.), the stored
      // anchor is no longer canonical and any already-generated future
      // instances are stale. Drop the anchor and clear future auto-generated
      // instances; the next generateRecurringEvents() run will re-anchor and
      // re-populate against the new rule.
      const previousRule = eventGroup.recurrence;
      const ruleMoved =
        updatedRecurrence &&
        previousRule &&
        (previousRule.frequency !== updatedRecurrence.frequency ||
          previousRule.dayOfWeek !== updatedRecurrence.dayOfWeek ||
          previousRule.monthlyType !== updatedRecurrence.monthlyType ||
          previousRule.dayOfMonth !== updatedRecurrence.dayOfMonth ||
          previousRule.nth !== updatedRecurrence.nth ||
          previousRule.time !== updatedRecurrence.time ||
          previousRule.timezone !== updatedRecurrence.timezone ||
          previousRule.durationMinutes !== updatedRecurrence.durationMinutes);

      const updatedEventGroup = {
        name: req.body.eventGroupName,
        description: req.body.eventGroupDescription,
        url: req.body.eventGroupURL,
        hostName: req.body.hostName,
        image: eventGroupImageFilename,
        showOnPublicList: groupData.publicBoolean,
        recurrence: updatedRecurrence,
      };

      await EventGroup.findOneAndUpdate(
        { id: req.params.eventGroupID },
        updatedEventGroup,
      );

      if (ruleMoved || (!updatedRecurrence && previousRule?.enabled)) {
        await clearFutureAutoGeneratedInstances(
          `group:${eventGroup._id.toString()}`,
        );
      }

      if (updatedRecurrence?.enabled) {
        generateRecurringEvents().catch((err) =>
          console.error(
            "Recurrence generation failed after group update:",
            err,
          ),
        );
      }

      addToLog(
        "editEventGroup",
        "success",
        "Event group " + req.params.eventGroupID + " edited",
      );

      res.sendStatus(200);
    } catch (err) {
      console.error(err);
      addToLog(
        "editEventGroup",
        "error",
        "Attempt to edit event group " +
          req.params.eventGroupID +
          " failed with error: " +
          err,
      );
      return res.status(500).json({
        errors: [
          {
            message: err,
          },
        ],
      });
    }
  },
);

// Accepts a JSON object of event/group IDs mapped to edit tokens.
// Returns an object of basic group data for each of the IDs
// which are valid groups and have an edit token which matches.
router.post("/known/groups", async (req: Request, res: Response) => {
  const known = req.body;
  if (!known) {
    return res.status(400).json({
      errors: [
        {
          message: "No known IDs were provided.",
        },
      ],
    });
  }

  try {
    const knownIDs = Object.keys(known);
    const groups = await EventGroup.find({
      id: { $in: knownIDs },
    });
    const knownGroups = groups.filter((group) => {
      return group.editToken === known[group.id];
    });
    const groupData = knownGroups.map((group) => {
      return {
        id: group.id,
        name: group.name,
        description: (
          marked.parse(group.description, {
            renderer: renderPlain(),
          }) as string
        )
          .split(" ")
          .splice(0, 40)
          .join(" ")
          .trim(),
        image: group.image,
        editToken: group.editToken,
        url: `/group/${group.id}`,
      };
    });
    return res.status(200).json(groupData);
  } catch (err) {
    console.error(err);
    addToLog(
      "getKnownGroups",
      "error",
      "Attempt to get known groups failed with error: " + err,
    );
    return res.status(500).json({
      errors: [
        {
          message: err,
        },
      ],
    });
  }
});

export default router;
